### ISSUE TITLE
Calibration process should log last calibration status to Redis

### ISSUE THREAD

**Issue by talonmyburgh** [COSMIC-SETI/COSMIC-VLA-DelayEngine#16]
Calibration process should log the following calibration information to Redis:

- timestamp of when calibration values were applied
- grade of gains from which calibration values were derived
- observation ID
- frequency information

**Comment by Chenoachem** [comment]
<img width="884" alt="image" src="https://github.com/COSMIC-SETI/COSMIC-VLA-DelayEngine/assets/18436454/e9bd06c8-f805-4852-b79c-2df0fb5a104d">
Our current "grade system" cannot distinguish between a low calibration grade due to the first time a frequency has been calibrated in a while so there are rapid phase wraps or if there is severe decoralation.  Having a method in place to be able to exclude recording when a low grade is recording is important but we don't want to implement it at this stage.  We should not record if the calibration is greater than 15 minutes old or if the current observational frequency is different from the last calibration frequency. It looks like both of those cases are covered in this dataset.

**Comment by talonmyburgh** [comment]
Addressed with [f567149](https://github.com/COSMIC-SETI/COSMIC-VLA-DelayEngine/commit/f56714904f2f503e64789f7027a1f1c40b1d1de2)

Once observations pick up again, we can assess if more or less must be logged.

**Comment by radonnachie** [comment]
![image](https://github.com/COSMIC-SETI/COSMIC-VLA-DelayEngine/assets/28019482/b133b25e-5d0f-4801-94ee-af4e727658fc)
these look decent but the grade is 11%...

**Comment by talonmyburgh** [comment]
These are not decent. There are very large phase jumps/differences between antenna. The per antenna grade might look good but the per channel grade would be very bad as it will note this phase jump difference. The overall grade will note this too.
